### ISSUE TITLE
[Application] : Erik Valle

### ISSUE THREAD

**Issue by moclas17** [fuel-champions/pro-applications#57]
### Proof of your code

https://github.com/moclas17/swaylings  - ETH Argentina 2023 project, this help to fuel to learn sway like rustlings
https://github.com/moclas17/certifik - ETH Bogota 2023 project, Api for help developers web2
https://github.com/moclas17/yhops (not web3, but api consumer of web3) 
https://github.com/moclas17/MateProject - ETH Waterloo 2023 project, make transactions on mainnet with 0 gasfee cost through mempool

### Activity on the Fuel forum

I am not active on https://forum.fuel.network/
but I took some online and in-person workshops with Cami Ramos and Sandusky

### Fuel Ambassador Program

No, I'm not a Fuel Ambassador

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
🎉 Congratulations! 🎉

You've been approved as a Pro in the Fuel Developer Champions Program! 🚀 We're thrilled to have you on board and can't wait to see your contributions.

👥 Please join the conversations happening right now in the Discussions at our GitHub organization: [Fuel Developer Champions Discussions](https://github.com/orgs/fuel-champions/discussions). It's a great place to connect, share, and learn with fellow champions.

📝 Also, don't miss out on the first bounty exclusively for champions! Check out the details here: [Technical Writing Bounty](https://github.com/fuel-champions/technical-writing-bounty) and kickstart your journey with us by making an impactful contribution.

We're excited to see your growth and achievements in the program. Welcome aboard, and let's fuel innovation together! 🌟
