### ISSUE TITLE
[Application] : Pro Application (secsec2025)

### ISSUE THREAD

**Issue by secsec2025** [fuel-champions/pro-applications#59]
### Proof of your code

I am stepping into building on Fuel and already feeling comfortable with using Sway.
https://github.com/secsec2025/sway-sample-contracts (A voting contract written in Sway)

Experience in blockchain indexing using **[SubSquid](https://docs.subsquid.io/)** and Graph
https://github.com/secsec2025/cryptopunks-subgraph-migration
https://github.com/secsec2025/lido-subgraph-migration
https://github.com/secsec2025/lens-subgraph-migration

### Activity on the Fuel forum

https://forum.fuel.network/u/secsec2025/summary

### Fuel Ambassador Program

No, I'm not a Fuel Ambassador

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
🎉 Congratulations! 🎉

You've been approved as a Pro in the Fuel Developer Champions Program! 🚀 We're thrilled to have you on board and can't wait to see your contributions.

👥 Please join the conversations happening right now in the Discussions at our GitHub organization: [Fuel Developer Champions Discussions](https://github.com/orgs/fuel-champions/discussions) and on the [Fuel Dev Champions Telegram Group](https://t.me/+FRKsID473_k5YWVk). They are great places to connect, share, and learn with fellow champions.

📝 Also, don't miss out on the first bounty exclusively for champions! Check out the details here: [Technical Writing Bounty](https://github.com/fuel-champions/technical-writing-bounty) and kickstart your journey with us by making an impactful contribution.

We're excited to see your growth and achievements in the program. Welcome aboard, and let's fuel innovation together! 🌟
