### ISSUE TITLE
[Application] : 

### ISSUE THREAD

**Issue by demoncash08** [fuel-champions/pro-applications#6]
### Proof of your code

https://github.com/demoncash08/LoyaltyRewardsDapp

Have not merged with opensource as of now but yes have done my share of work in web3. I have also used account abstraction and even understood the working of the dexes along with ENS workflow and can recreate them. 

### Activity on the Fuel forum

Sorry was not active on the fuel forum but yes was really active in the development and learning something new every week. I believe I would be a great addition to the team if I am given an opportunity.

### Fuel Ambassador Program

No, I'm not a Fuel Ambassador

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
🎉 Congratulations! 🎉

You've been approved as a Pro in the Fuel Developer Champions Program! 🚀 We're thrilled to have you on board and can't wait to see your contributions.

👥 Please join the conversations happening right now in the Discussions at our GitHub organization: [Fuel Developer Champions Discussions](https://github.com/orgs/fuel-champions/discussions). It's a great place to connect, share, and learn with fellow champions.

📝 Also, don't miss out on the first bounty exclusively for champions! Check out the details here: [Technical Writing Bounty](https://github.com/fuel-champions/technical-writing-bounty) and kickstart your journey with us by making an impactful contribution.

We're excited to see your growth and achievements in the program. Welcome aboard, and let's fuel innovation together! 🌟
