### ISSUE TITLE
[Application] : 

### ISSUE THREAD

**Issue by PhiloCwh** [fuel-champions/pro-applications#60]
### Proof of your code

https://github.com/PhiloCwh/Web3-Financial-Engineering-Courses 
the first class about the Web3-Financial-Engineering-Courses 
web3 defi teaches vedio courses
video link：
youtube：https://www.youtube.com/channel/UCPMvS2rBDyTxQKHyBeiHvKg
blibli：https://space.bilibili.com/323920542/channel/collectiondetail?sid=1078973

https://github.com/PhiloCwh/ETHHangzhou
ETHHANZOU hackthon Oct 16, 2023

https://github.com/PhiloCwh/ETHBeijing
ETHBEIJING hackthon  Apr 8, 2023

https://github.com/PhiloCwh/NFC
nft liquidity solutions Apr 8, 2023

so on in github 
https://github.com/PhiloCwh?tab=repositories

### Activity on the Fuel forum

no active, but i want to upload something abount sway learning class
https://forum.fuel.network/u/philocwh/summary

### Fuel Ambassador Program

None

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
🎉 Congratulations! 🎉

You've been approved as a Pro in the Fuel Developer Champions Program! 🚀 We're thrilled to have you on board and can't wait to see your contributions.

👥 Please join the conversations happening right now in the Discussions at our GitHub organization: [Fuel Developer Champions Discussions](https://github.com/orgs/fuel-champions/discussions) and on the [Fuel Dev Champions Telegram Group](https://t.me/+FRKsID473_k5YWVk). They are great places to connect, share, and learn with fellow champions.

📝 Also, don't miss out on the first bounty exclusively for champions! Check out the details here: [Technical Writing Bounty](https://github.com/fuel-champions/technical-writing-bounty) and kickstart your journey with us by making an impactful contribution.

We're excited to see your growth and achievements in the program. Welcome aboard, and let's fuel innovation together! 🌟

**Comment by PhiloCwh** [comment]
thx
