### ISSUE TITLE
[Application] : Pro Application Clean99

### ISSUE THREAD

**Issue by clean99** [fuel-champions/pro-applications#62]
### Proof of your code

BTC on-chain generative gaming arts: https://github.com/clean99/birdy
Blockchain in js: https://github.com/clean99/blockchain-in-js

### Activity on the Fuel forum

https://forum.fuel.network/u/clean99/activity

### Fuel Ambassador Program

None

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
🎉 Congratulations! 🎉

You've been approved as a Pro in the Fuel Developer Champions Program! 🚀 We're thrilled to have you on board and can't wait to see your contributions.

👥 Please join the conversations happening right now in the Discussions at our GitHub organization: [Fuel Developer Champions Discussions](https://github.com/orgs/fuel-champions/discussions) and on the [Fuel Dev Champions Telegram Group](https://t.me/+FRKsID473_k5YWVk). They are great places to connect, share, and learn with fellow champions.

📝 Also, don't miss out on the first bounty exclusively for champions! Check out the details here: [Technical Writing Bounty](https://github.com/fuel-champions/technical-writing-bounty) and kickstart your journey with us by making an impactful contribution.

We're excited to see your growth and achievements in the program. Welcome aboard, and let's fuel innovation together! 🌟
