### ISSUE TITLE
[Pro Application] : 

### ISSUE THREAD

**Issue by Khadeeejah** [fuel-champions/pro-applications#67]
### Proof of your code

I have not contributed recently to any open source web 3 project in the past three months, a few of them are private projects but i can show some of my technical documentation open source projects and a web2 project
(https://github.com/miraclx/freyr-js/pull/624)
(https://docs.pakt.world/pakt)
(https://github.com/celo-org/docs/pull/784)
(https://github.com/LazerpayHQ/Lazerpay-documentation-v2/pull/26)
(https://docs.lazerpay.finance/home)

### Activity on the Fuel forum

I attended the How to Teach Sway Language workshop, and that was how i got to know about the forum. i have joined and will start making meaningful contributions.
(https://forum.fuel.network/u/khadeeejah)

### Fuel Ambassador Program

No, I'm not a Fuel Ambassador

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
🎉 Congratulations! 🎉

You've been approved as a Pro in the Fuel Developer Champions Program! 🚀 We're thrilled to have you on board and can't wait to see your contributions.

👥 Please join the conversations happening right now in the Discussions at our GitHub organization: [Fuel Developer Champions Discussions](https://github.com/orgs/fuel-champions/discussions) and on the [Fuel Dev Champions Telegram Group](https://t.me/+FRKsID473_k5YWVk). They are great places to connect, share, and learn with fellow champions.

📝 Also, don't miss out on the bounties exclusively for champions! Check out the details here: [Technical Writing Bounty](https://github.com/fuel-champions/technical-writing-bounty) and here: [Sway Workshop Bounty](https://github.com/fuel-champions/workshop-bounty) and kickstart your journey with us by making an impactful contribution.

We're excited to see your growth and achievements in the program. Welcome aboard, and let's fuel innovation together! 🌟
