### ISSUE TITLE
[Application] : For Fuel Championship program as a web3 developer and technical writer

### ISSUE THREAD

**Issue by Phenzic** [fuel-champions/pro-applications#9]
### Proof of your code

PR to Celo Docs: https://github.com/celo-org/docs/pull/976
PR Reviews @celo
![image](https://github.com/fuel-champions/pro-applications/assets/69092079/7f1a3eb0-aa83-45ea-9367-97529d2c0696)
![image](https://github.com/fuel-champions/pro-applications/assets/69092079/14857fc6-3197-42de-9238-3a8fec28a216)

Playing around and contributing to other web3 dev tools and protocols: 
![image](https://github.com/fuel-champions/pro-applications/assets/69092079/b1960324-ecec-4658-a263-f6b9af02c7ea)
https://github.com/catapulta-sh/catapulta-hardhat-template/issues/2
https://github.com/balancer/balancer-sdk/issues/562

### Activity on the Fuel forum

Didn't have one
Just joined in 🥂 
https://github.com/balancer/balancer-sdk/issues/562

### Fuel Ambassador Program

No, I'm not a Fuel Ambassador

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
🎉 Congratulations! 🎉

You've been approved as a Pro in the Fuel Developer Champions Program! 🚀 We're thrilled to have you on board and can't wait to see your contributions.

👥 Please join the conversations happening right now in the Discussions at our GitHub organization: [Fuel Developer Champions Discussions](https://github.com/orgs/fuel-champions/discussions). It's a great place to connect, share, and learn with fellow champions.

📝 Also, don't miss out on the first bounty exclusively for champions! Check out the details here: [Technical Writing Bounty](https://github.com/fuel-champions/technical-writing-bounty) and kickstart your journey with us by making an impactful contribution.

We're excited to see your growth and achievements in the program. Welcome aboard, and let's fuel innovation together! 🌟
